/*
 * spell-words.js — the SPELLING BEE word list.
 *
 * Each entry is [word, picture, clue]. The picture does most of the work for a
 * child who cannot read the clue yet, so every word has one that actually looks
 * like the thing. Clues are one short sentence, never a definition.
 *
 * Banded by length. Kept in its own file because it is data, not game, and
 * because tools/phrases.js reads it to work out what audio to record.
 */
(function (global) {
  'use strict';

  var THREE = [
    ['cat', '🐱', 'It says meow and has whiskers'],
    ['dog', '🐶', 'It says woof and wags its tail'],
    ['sun', '☀️', 'Hot and yellow, up in the sky'],
    ['bus', '🚌', 'A big one takes you to school'],
    ['cow', '🐮', 'It says moo and gives us milk'],
    ['pig', '🐷', 'It is pink and says oink'],
    ['bee', '🐝', 'It buzzes and makes honey'],
    ['fox', '🦊', 'Orange, with a big bushy tail'],
    ['owl', '🦉', 'A bird that hoots at night'],
    ['egg', '🥚', 'A chicken lays one'],
    ['hat', '🎩', 'You wear it on your head'],
    ['cup', '☕', 'You drink out of it'],
    ['bed', '🛏️', 'You sleep in it'],
    ['key', '🔑', 'It opens a door'],
    ['car', '🚗', 'You drive it down the road'],
    ['van', '🚐', 'A big car for carrying things'],
    ['jam', '🍓', 'Sweet and red, you spread it on toast'],
    ['net', '🥅', 'You catch a fish with one'],
    ['map', '🗺️', 'It shows you the way'],
    ['leg', '🦵', 'You have two, and you walk on them'],
    ['ear', '👂', 'You hear with it'],
    ['eye', '👁️', 'You see with it'],
    ['toe', '🦶', 'There are five on each foot'],
    ['jug', '🫗', 'You pour milk out of it'],
    ['pan', '🍳', 'You cook eggs in it'],
    ['pot', '🍲', 'You cook soup in it'],
    ['pen', '🖊️', 'You write with it'],
    ['mug', '🍵', 'A big cup with a handle'],
    ['bag', '👜', 'You carry your things in it'],
    ['box', '📦', 'A parcel comes in one'],
    ['top', '👕', 'You wear it on your top half'],
    ['hop', '🐰', 'A rabbit does it'],
    ['run', '🏃', 'Move your legs very fast'],
    ['sit', '🪑', 'What you do on a chair'],
    ['big', '🐘', 'The opposite of small'],
    ['red', '🍎', 'The colour of a strawberry'],
    ['hot', '🔥', 'Too warm to touch'],
    ['wet', '💦', 'Covered in water'],
    ['mud', '🐖', 'Wet dirt you can splash in'],
    ['log', '🪵', 'A piece of a tree'],
    ['bat', '🦇', 'It flies at night and hangs upside down'],
    ['rat', '🐀', 'A big mouse with a long tail'],
    ['bug', '🐛', 'A tiny creepy crawly'],
    ['ant', '🐜', 'A tiny insect that lives in a nest'],
    ['fly', '🪰', 'It buzzes round the room'],
    ['hen', '🐔', 'A lady chicken'],
    ['cub', '🐻', 'A baby bear'],
    ['pup', '🐕', 'A baby dog'],
    ['nut', '🥜', 'A squirrel buries them'],
    ['bun', '🍞', 'A little round bread'],
    ['pie', '🥧', 'Apple ones are lovely'],
    ['tea', '🫖', 'A hot drink in a cup'],
    ['ice', '🧊', 'Frozen water'],
    ['ham', '🍖', 'Pink meat in a sandwich'],
    ['web', '🕸️', 'A spider spins one'],
    ['fan', '🌬️', 'It blows air to cool you down'],
    ['bin', '🗑️', 'Rubbish goes in it'],
    ['lid', '🫙', 'The top of a jar'],
    ['tap', '🚰', 'Water comes out of it'],
    ['tin', '🥫', 'Beans come in one'],
    ['toy', '🧸', 'Something you play with'],
    ['bow', '🎀', 'You tie it in your hair'],
    ['sea', '🌊', 'Salty water with waves'],
    ['sky', '🌌', 'Up above the clouds'],
    ['pea', '🫛', 'A tiny green vegetable'],
    ['cap', '🧢', 'A hat with a peak'],
    ['zip', '🧥', 'It does your coat up'],
    ['lip', '👄', 'Part of your mouth'],
    ['arm', '💪', 'Your hand is on the end of it'],
    ['cot', '🍼', 'A little bed for a baby'],
    ['mat', '🧘', 'You wipe your feet on it'],
    ['rug', '🧶', 'A little carpet'],
    ['pin', '📌', 'A tiny sharp thing'],
    ['saw', '🪚', 'A tool for cutting wood'],
    ['axe', '🪓', 'For chopping wood'],
    ['jet', '✈️', 'A very fast plane'],
    ['kit', '🎒', 'A bag of the things you need'],
    ['yak', '🐂', 'A big shaggy animal'],
    ['cod', '🐟', 'A kind of fish'],
    ['eel', '🐍', 'A long fish like a snake'],
    ['ram', '🐏', 'A sheep with curly horns'],
    ['doe', '🦌', 'A lady deer'],
    ['hog', '🐗', 'Another word for a pig'],
    ['elf', '🧝', 'A tiny helper at Christmas'],
    ['gum', '🍬', 'You chew it but never swallow it'],
    ['ivy', '🌿', 'A green plant that climbs up walls'],
    ['oak', '🌳', 'A big strong tree'],
    ['bud', '🌷', 'A flower before it opens'],
    ['hay', '🌾', 'Dried grass that horses eat'],
    ['den', '🦡', 'Where a fox or a badger lives'],
    ['zoo', '🦁', 'Where you go to see the animals'],
    ['dig', '🕳️', 'Make a hole in the ground'],
    ['mix', '🥣', 'Stir it all up together'],
    ['cut', '✂️', 'What scissors do'],
    ['hug', '🤗', 'Put your arms round someone'],
    ['sad', '😢', 'The opposite of happy'],
    ['wig', '💇', 'Pretend hair you put on'],
    ['fin', '🐠', 'A fish swims with it'],
    ['paw', '🐾', "A cat's foot"],
    ['tub', '🛁', 'You have a bath in it']
  ];

  var FOUR = [
    ['fish', '🐟', 'It swims and has fins'],
    ['cake', '🎂', 'You eat it on your birthday'],
    ['star', '⭐', 'It twinkles in the night sky'],
    ['moon', '🌙', 'It shines at night and is round'],
    ['tree', '🌳', 'Tall and green, with leaves'],
    ['frog', '🐸', 'It is green and hops'],
    ['book', '📚', 'You read it at bedtime'],
    ['duck', '🦆', 'It says quack and likes ponds'],
    ['bear', '🐻', 'A big furry animal that likes honey'],
    ['milk', '🥛', 'A white drink from a cow'],
    ['ball', '⚽', 'You kick it or throw it'],
    ['rain', '🌧️', 'Water falling from the clouds'],
    ['snow', '❄️', 'White and cold, you build with it'],
    ['lion', '🦁', 'The king of the jungle, it roars'],
    ['shoe', '👟', 'You put it on your foot'],
    ['bird', '🐦', 'It has wings and sings'],
    ['door', '🚪', 'You open it to go in'],
    ['king', '🤴', 'He wears a crown'],
    ['nest', '🪹', 'Where a bird lays its eggs'],
    ['sock', '🧦', 'It goes on your foot inside your shoe'],
    ['hand', '✋', 'It has five fingers'],
    ['foot', '🦶', 'You stand on it'],
    ['head', '🧠', 'Your hair grows on it'],
    ['hair', '💇', 'It grows on your head'],
    ['nose', '👃', 'You smell with it'],
    ['lamb', '🐑', 'A baby sheep'],
    ['goat', '🐐', 'It has horns and eats everything'],
    ['deer', '🦌', 'It runs in the forest'],
    ['swan', '🦢', 'A big white bird on the lake'],
    ['crab', '🦀', 'It walks sideways on the beach'],
    ['worm', '🪱', 'Long and wiggly, it lives in the mud'],
    ['moth', '🦋', 'Like a butterfly, but it flies at night'],
    ['wasp', '🐝', 'Yellow and black, and it stings'],
    ['mole', '🦫', 'It digs tunnels under the grass'],
    ['seal', '🦭', 'It claps its flippers and swims'],
    ['bell', '🔔', 'It rings ding dong'],
    ['boat', '⛵', 'It floats on the water'],
    ['ship', '🚢', 'A very big boat'],
    ['kite', '🪁', 'It flies on a string in the wind'],
    ['drum', '🥁', 'You bang it to make a noise'],
    ['flag', '🚩', 'It waves on a pole'],
    ['doll', '🪆', 'A toy that looks like a person'],
    ['ring', '💍', 'You wear it on your finger'],
    ['gift', '🎁', 'A present with a bow on it'],
    ['lamp', '💡', 'It lights up the room'],
    ['sofa', '🛋️', 'A long soft seat'],
    ['desk', '🪑', 'A table you write at'],
    ['fork', '🍴', 'You eat with it'],
    ['soup', '🍲', 'You eat it hot with a spoon'],
    ['rice', '🍚', 'Little white grains you eat'],
    ['corn', '🌽', 'Yellow, and it grows on a cob'],
    ['bean', '🫘', 'You have them on toast'],
    ['pear', '🍐', 'A green fruit, fat at the bottom'],
    ['plum', '🫐', 'A small purple fruit'],
    ['lime', '🍋', 'A little green lemon'],
    ['kiwi', '🥝', 'Furry outside, green inside'],
    ['cave', '🕳️', 'A big hole in a hill'],
    ['hill', '⛰️', 'A little mountain'],
    ['lake', '🏞️', 'Water with land all round it'],
    ['sand', '🏖️', 'You build castles with it'],
    ['rock', '🪨', 'A big hard stone'],
    ['leaf', '🍃', 'It grows on a tree and falls in autumn'],
    ['seed', '🌱', 'Plant it and it grows'],
    ['wood', '🪵', 'What a tree is made of'],
    ['barn', '🚜', 'A big shed on a farm'],
    ['farm', '🐄', 'Where the cows and sheep live'],
    ['gate', '🚧', 'A door in a fence'],
    ['road', '🛣️', 'Cars drive along it'],
    ['park', '🛝', 'Grass and swings to play on'],
    ['bike', '🚲', 'Two wheels and you pedal'],
    ['bath', '🛁', 'You wash in it'],
    ['soap', '🧼', 'It makes bubbles when you wash'],
    ['comb', '💈', 'You tidy your hair with it'],
    ['coat', '🧥', 'You wear it when it is cold'],
    ['belt', '🪢', 'It holds your trousers up'],
    ['boot', '🥾', 'A big shoe for muddy puddles'],
    ['cook', '👨‍🍳', 'Make the dinner'],
    ['bake', '🧁', 'Make cakes in the oven'],
    ['wash', '🧽', 'Get it clean with water'],
    ['jump', '🤸', 'Push off the ground with both feet'],
    ['walk', '🚶', 'Go along, one foot then the other'],
    ['skip', '🪢', 'Hop along with a rope'],
    ['swim', '🏊', 'Move along in the water'],
    ['sing', '🎤', 'Make a song with your voice'],
    ['read', '📖', 'Look at the words in a book'],
    ['draw', '🖍️', 'Make a picture with a crayon'],
    ['play', '🧸', 'What you do with your toys'],
    ['clap', '👏', 'Bang your hands together'],
    ['warm', '🧣', 'A little bit hot'],
    ['cold', '🥶', 'The opposite of hot'],
    ['dark', '🌑', 'When you cannot see anything'],
    ['blue', '💙', 'The colour of the sky'],
    ['pink', '🩷', 'The colour of a pig'],
    ['gold', '🏅', 'Shiny and yellow, and worth a lot'],
    ['grey', '🐘', 'The colour of an elephant'],
    ['baby', '👶', 'A very little person'],
    ['girl', '👧', 'A young lady'],
    ['time', '⏰', 'The clock tells you it'],
    ['year', '📅', 'Twelve months all together'],
    ['tent', '⛺', 'You sleep in it when you go camping']
  ];

  var FIVE = [
    ['apple', '🍎', 'A red fruit that grows on a tree'],
    ['house', '🏠', 'You live in one'],
    ['horse', '🐴', 'You can ride it, it says neigh'],
    ['sheep', '🐑', 'Woolly, and it says baa'],
    ['bread', '🍞', 'You make toast out of it'],
    ['water', '💧', 'You drink it and it has no colour'],
    ['happy', '😊', 'How you feel when you smile'],
    ['chair', '🪑', 'You sit on it'],
    ['cloud', '☁️', 'White and fluffy in the sky'],
    ['green', '💚', 'The colour of the grass'],
    ['mouse', '🐭', 'A tiny animal that likes cheese'],
    ['teeth', '🦷', 'You brush them every night'],
    ['train', '🚂', 'It runs along a track, choo choo'],
    ['beach', '🏖️', 'Sand and sea, where you build castles'],
    ['queen', '👑', 'She wears a crown'],
    ['smile', '🙂', 'What your mouth does when you are happy'],
    ['tiger', '🐯', 'Orange with black stripes'],
    ['zebra', '🦓', 'A horse with black and white stripes'],
    ['panda', '🐼', 'Black and white, and it eats bamboo'],
    ['koala', '🐨', 'It hugs a tree and sleeps all day'],
    ['snake', '🐍', 'Long, with no legs at all'],
    ['whale', '🐳', 'The biggest animal in the sea'],
    ['shark', '🦈', 'It has lots of sharp teeth'],
    ['robin', '🐦', 'A little bird with a red front'],
    ['puppy', '🐶', 'A baby dog'],
    ['bunny', '🐰', 'Another word for a rabbit'],
    ['sweet', '🍬', 'A little treat, and very sugary'],
    ['honey', '🍯', 'Sticky and gold, the bees make it'],
    ['lemon', '🍋', 'Yellow, and very sour'],
    ['grape', '🍇', 'A tiny round fruit in a bunch'],
    ['peach', '🍑', 'Furry outside and sweet inside'],
    ['melon', '🍈', 'A big round fruit full of juice'],
    ['berry', '🫐', 'A tiny fruit off a bush'],
    ['pizza', '🍕', 'Round, with cheese on top'],
    ['salad', '🥗', 'A bowl of green leaves'],
    ['juice', '🧃', 'A drink squeezed out of fruit'],
    ['spoon', '🥄', 'You eat your pudding with it'],
    ['knife', '🔪', 'It cuts your food'],
    ['plate', '🍽️', 'Your dinner sits on it'],
    ['glass', '🥛', 'You drink out of it and you can see through it'],
    ['clock', '🕐', 'It tells you the time'],
    ['brush', '🪥', 'You clean your teeth with it'],
    ['plant', '🪴', 'It grows in a pot'],
    ['grass', '🌱', 'Green, and it grows in the garden'],
    ['river', '🏞️', 'Water running along to the sea'],
    ['storm', '⛈️', 'Thunder and lightning together'],
    ['light', '💡', 'You switch it on when it is dark'],
    ['night', '🌜', 'When it is dark and you go to bed'],
    ['dream', '💭', 'The story in your head while you sleep'],
    ['music', '🎵', 'Something lovely to listen to']
  ];

  var SIX = [
    ['rabbit', '🐰', 'It hops and loves carrots'],
    ['garden', '🌷', 'Outside, where the flowers grow'],
    ['monkey', '🐵', 'It swings in trees and likes bananas'],
    ['yellow', '💛', 'The colour of the sun'],
    ['orange', '🍊', 'A fruit, and a colour'],
    ['purple', '💜', 'Mix red and blue and you get it'],
    ['flower', '🌸', 'It grows in the garden and smells lovely'],
    ['banana', '🍌', 'A long yellow fruit you peel'],
    ['dragon', '🐉', 'A big one breathes fire in stories'],
    ['castle', '🏰', 'Where a king and queen live'],
    ['pencil', '✏️', 'You write and draw with it'],
    ['spider', '🕷️', 'Eight legs, and it spins a web'],
    ['turtle', '🐢', 'It walks slowly and carries its house'],
    ['winter', '⛄', 'The cold time when it snows'],
    ['school', '🏫', 'Where you go to learn'],
    ['sister', '👧', 'A girl in your family'],
    ['mother', '👩', 'Your mum'],
    ['father', '👨', 'Your dad'],
    ['friend', '🧑‍🤝‍🧑', 'Someone you like to play with'],
    ['people', '👨‍👩‍👧', 'More than one person'],
    ['summer', '🌞', 'The hot time when school stops'],
    ['spring', '🌷', 'When the flowers come out again'],
    ['autumn', '🍂', 'When the leaves go brown and fall'],
    ['forest', '🌲', 'Lots and lots of trees'],
    ['jumper', '🧶', 'A warm woolly top'],
    ['jacket', '🧥', 'A coat that is not very long'],
    ['button', '🔘', 'You do your coat up with it'],
    ['pocket', '👖', 'A little bag in your trousers'],
    ['bucket', '🪣', 'You carry water in it'],
    ['ladder', '🪜', 'You climb up it'],
    ['window', '🪟', 'You look out of it'],
    ['pillow', '🛏️', 'You put your head on it'],
    ['carpet', '🧶', 'It covers the floor'],
    ['mirror', '🪞', 'You see yourself in it'],
    ['bottle', '🍼', 'A baby drinks out of one'],
    ['basket', '🧺', 'You carry the shopping in it'],
    ['cheese', '🧀', 'Yellow, and a mouse would love it'],
    ['butter', '🧈', 'You spread it on your bread'],
    ['carrot', '🥕', 'Long and orange, a rabbit loves them'],
    ['potato', '🥔', 'You make chips out of it'],
    ['tomato', '🍅', 'Round and red, and it goes in a salad'],
    ['cherry', '🍒', 'A tiny red fruit with a stone in it'],
    ['muffin', '🧁', 'A little cake you eat for breakfast'],
    ['dinner', '🍽️', 'The big meal in the evening'],
    ['bridge', '🌉', 'It goes over the river'],
    ['island', '🏝️', 'Land with sea all round it'],
    ['desert', '🏜️', 'Hot sand as far as you can see'],
    ['jungle', '🌴', 'A hot forest full of animals'],
    ['planet', '🪐', 'A big round world in space'],
    ['rocket', '🚀', 'It flies all the way to space'],
    ['guitar', '🎸', 'You play it with your fingers'],
    ['violin', '🎻', 'You play it with a bow'],
    ['puppet', '🎭', 'A toy you move with your hand'],
    ['crayon', '🖍️', 'A fat coloured stick for drawing'],
    ['parcel', '📦', 'A present in the post'],
    ['candle', '🕯️', 'It has a little flame on top'],
    ['ribbon', '🎀', 'Long and thin, you tie it in a bow'],
    ['tunnel', '🚇', 'A road that goes through a hill'],
    ['engine', '🚂', 'The bit of the train that pulls'],
    ['saddle', '🐴', 'You sit on it to ride a horse'],
    ['kitten', '🐱', 'A baby cat'],
    ['donkey', '🫏', 'Like a little horse with long ears'],
    ['parrot', '🦜', 'A bright bird that talks'],
    ['beaver', '🦫', 'It builds a dam out of sticks'],
    ['badger', '🦡', 'Black and white, and it comes out at night'],
    ['insect', '🐞', 'A tiny creature with six legs']
  ];

  var SEVEN = [
    ['penguin', '🐧', 'A black and white bird that cannot fly'],
    ['giraffe', '🦒', 'It has the longest neck of all'],
    ['rainbow', '🌈', 'Colours in the sky after the rain'],
    ['dolphin', '🐬', 'A clever animal that swims and squeaks'],
    ['kitchen', '🍳', 'The room where you cook'],
    ['chicken', '🐔', 'It clucks and lays eggs'],
    ['brother', '👦', 'A boy in your family'],
    ['morning', '🌅', 'The start of the day'],
    ['blanket', '🛌', 'It keeps you warm in bed'],
    ['cupcake', '🧁', 'A little cake with icing on top'],
    ['balloon', '🎈', 'You blow it up and it floats away'],
    ['bicycle', '🚲', 'Two wheels and you pedal'],
    ['unicorn', '🦄', 'A magic horse with a horn'],
    ['pumpkin', '🎃', 'Big and orange, you carve a face in it'],
    ['sausage', '🌭', 'Long and pink, you fry it'],
    ['pancake', '🥞', 'Flat, and you flip it in a pan'],
    ['popcorn', '🍿', 'It goes pop and you eat it at the film'],
    ['picture', '🖼️', 'A drawing you hang on the wall'],
    ['present', '🎁', 'A parcel with a ribbon on it'],
    ['holiday', '🏖️', 'When you go away and have fun'],
    ['biscuit', '🍪', 'You dunk it in your tea'],
    ['sticker', '🌟', 'You get one when you have done well'],
    ['leopard', '🐆', 'A big cat covered in spots'],
    ['peacock', '🦚', 'It has a huge fan of blue feathers']
  ];

  var BIG = [
    ['elephant', '🐘', 'The biggest animal, with a long trunk'],
    ['birthday', '🎁', 'The day you get cake and presents'],
    ['sandwich', '🥪', 'Two bits of bread with a filling'],
    ['princess', '👸', 'A king and queen’s daughter'],
    ['football', '⚽', 'A game you play with your feet'],
    ['mountain', '⛰️', 'A very big hill you can climb'],
    ['dinosaur', '🦕', 'A huge animal from long, long ago'],
    ['umbrella', '☂️', 'It keeps the rain off you'],
    ['kangaroo', '🦘', 'It hops and keeps its baby in a pocket'],
    ['starfish', '⭐', 'It has five arms and lives in the sea'],
    ['snowball', '⛄', 'You squash the snow into a ball'],
    ['Christmas', '🎄', 'The day with a tree and presents'],
    ['butterfly', '🦋', 'It was a caterpillar first'],
    ['chocolate', '🍫', 'Brown and sweet, it melts in your mouth'],
    ['crocodile', '🐊', 'A big green snappy one lives in rivers'],
    ['pineapple', '🍍', 'A spiky fruit with a leafy top'],
    ['astronaut', '👨‍🚀', 'Someone who flies up into space'],
    ['telescope', '🔭', 'You look through it to see the stars'],
    ['squirrel', '🐿️', 'It has a bushy tail and buries nuts'],
    ['scarecrow', '🌾', 'It stands in a field to frighten the birds']
  ];

  global.SpellWords = [THREE, FOUR, FIVE, SIX, SEVEN, BIG];
})(window);
